### ISSUE TITLE
Misspelled command name

### ISSUE THREAD

**Issue by sorsted** [rallg/novel#1]
Hello,

Great class! But in the file `novel-Fonts.sty`, you have misspelled the command `\space` as `\sapce` on line 311. Just thought I’d let you know.

Also, should we think of `novelette` as the successor to `novel`? Is it “better” than `novel` for what it does?

P.S. It was very difficult to find this repository and to find contact information on you to report this bug. You might want to add a link to this repository on CTAN. 😉

**Comment by rallg** [comment]
Good catch! I will make the correction, and upload it to CTAN when I get the chance. Probably will not be in the system until 3 days from now. Meanwhile, you can make the manual correction in the distro code, without hurting anything.

Regarding Novelette: It is far from complete, because I am still tinkering with the command structure. You may play with it, but do not use for anything real, because newer code may cause issues with older documents.

Novelette is "better" in the sense that its target audience will be writers who know very little about TeX. In fact, it would be best if they knew nothing about TeX, other than how to install it and use command line (or TeXworks). It actually does less than Novel, but does "what you need to to" for writing popular fiction (detective novels, etc.). On the other Hand, Novel allows some fancy things that are almost never seen in popular fiction. But to do that, the command structure of Novel is more complex.

My development code for Novelette (not yet posted here at GitHub) has some very precise layout code, better than already-posted code, and better than Novel. If I am satisfied with it, I may also build it into Novel.

Thanks to folks at tex.stackexchange.com, I have learned how to do a few things that are very obscure. Using LuaLaTeX is most helpful.
