### ISSUE TITLE
Error in the documentation, about encoding

### ISSUE THREAD

**Issue by quark67** [rallg/novel#2]
At https://github.com/rallg/novel/blob/main/doc/lualatex/novel/novel-documentation.html, on line 608, we read:

```html
You must create your document in <span style="white-space:nowrap">utf-8</span> encoding. No OT1, no T1, no LY1, or other TeX font encoding that pre-dates cell phones. Do not call for <i>fontenc</i> in your Preamble, because <span style="white-space:nowrap">utf-8</span> is <span style="white-space:nowrap">pre-configured</span>
```

But, utf8 has nothing to do with OT1, T1 or LY1.

The former is an INPUT enc (`\usepackage[utf8]{inputenc}`), and the latter is a FONT enc (`\usepackage[T1]{fontenc}`).

**INPUT enc** is for the encoding of the .tex file (http://mirrors.ctan.org/macros/latex/base/inputenc.pdf).

**FONT enc** is for the encoding of the font set (http://mirrors.ctan.org/macros/latex/base/encguide.pdf).

I don't know very well LuaLaTeX, there is no `\usepackage[...]{fontenc}` on LuaLaTeX, but I doubt that on LuaLaTeX you can use something like `\usepackage[T1]{inputenc}`... So it's better to correct this paragraph of your documentation.

**Comment by rallg** [comment]
Good catch. When I get around to it, I will fix the HTML. Although several
books have been published using novel, by several authors, nobody noticed
that for 5 years!

The document must be typed in utf-8. The Novel document class relies on
some features that are only present in OpenType fonts (and many TrueType),
but cannot be found in the
older Type 1 fonts. So what I should have written was "document must be
uft-8, fonts must be OpenType or TrueType" and not mentioned font encoding
at all.

IMPORTANT: If you are using TeXlive 2022, there is a bug in novel version
1.80, fixed in version 1.81. Although 1.81 is at CTAN, you cannot get it by
updating TeXlive 2022.
The simple fix is at my GitHub page for novel: github.com/rallg/novel


- R.A.
