### ISSUE TITLE
Use babel instead of polyglossia

### ISSUE THREAD

**Issue by sorsted** [rallg/novel#2]
In the distant past, `polyglossia` was supposed to be the replacement of `babel` for LuaTeX. But according to the people at TeX.SX, this is not the case anymore. Development of `polyglossia` stagnated while `babel` gained proper LuaTeX support, so now `babel` is once again the recommended solution. I suggest that you at least allow us to use that instead.

**Comment by rallg** [comment]
That is very possible. I intended to issue a minor doc update sometime in mid-January 2024. Between now and then, I will see whether I can enable babel without too much code overhaul (allow either babel or polyglossia). If so, I will do it. If not, I will report back.

As you noted, there was a time when polyglossia was ahead of babel, for lualatex. Also, I found the polyglossia documentation easier to understand, from the point of view of writers who do not regularly use TeX. It is still the case that P docs are easier than B docs, for the limited purpose of novel.

Meanwhle, if you know how to hack the code for your own purposes, go ahead and do it. Keep a copy of your hacked code, in case the update does not have babel.

In any case: Avoid using babel shortcuts, especially the one that use double quotes ("). This is because novels often have a lot of dialog, and it is harder to detect typos when characters may have more than one meaning.
